### ISSUE TITLE
Update whole-body-controllers

### ISSUE THREAD

**Issue by gabrielenava** [robotology/whole-body-controllers#33]
A general update is required to address several issues and to properly deal with new features such as the [autogenerated Yoga++](https://github.com/loc2/component_wholebody-teleoperation/issues/99#issuecomment-397602834). In particular, this is the list of issues that is necessary to address: 

### This repo

- [x] [New features and legacy](https://github.com/robotology/whole-body-controllers/issues/23)
- [x] [Improve the visualization and data collection](https://github.com/robotology/whole-body-controllers/issues/27)
- [x] [Get YARP_ROBOT_NAME from the system instead of overwriting it](https://github.com/robotology/whole-body-controllers/issues/30)
- [x] [Use QP block from WBToolbox in the controllers](https://github.com/robotology/whole-body-controllers/issues/28)
- [x] [Cleanup wholeBodyDynamics port names](https://github.com/robotology/whole-body-controllers/issues/34)

### Loc2

- [x] Use different notation for the centroidal momentum
- ~~[ ] Test auto-generated Yoga++ running from icub-head of iCubGenova04~~

**Comment by gabrielenava** [comment]
This update session is complete. Closing.
