### ISSUE TITLE
Whole Body Controllers Release 2.5

### ISSUE THREAD

**Issue by gabrielenava** [robotology/whole-body-controllers#70]
The 2.5 release of whole-body-controllers will **NOT** change the current repo structure, but will mainly be focused on adding **new features**. It will be an ambitious release, so it will probably take some time to be achieved. Here is the list of changes:

- [x] [support data processing of data coming from Simulink](https://github.com/robotology/whole-body-controllers/issues/20)
- [x] [avoid to recompile the model when using the static GUI](https://github.com/robotology/whole-body-controllers/issues/82)
- [x] [print joint name when a spike occurs](https://github.com/robotology/whole-body-controllers/issues/81)
- [x] ~[support runtime plots](https://github.com/robotology/whole-body-controllers/issues/20)~
- [x] ~[extend the `wbc` library by collecting other utility functions from other repositories](https://github.com/robotology/whole-body-controllers/issues/71)~
- [x] ~[include the momentum jerk control](https://github.com/robotology/whole-body-controllers/issues/72)~
- [x] ~[include the friction exploitation control](https://github.com/robotology/whole-body-controllers/issues/73)~
- [x] ~[include joystick interface for the yoga](https://github.com/robotology/whole-body-controllers/issues/66)~
- [x] ~[include `matlab-multi-body-sim`](https://github.com/robotology/whole-body-controllers/issues/74)~
- [x] ~[automatize as much as possible the simulation procedure with Gazebo](https://github.com/robotology/whole-body-controllers/issues/76)~
- [x] [properly document or simplify the procedure for adding `wbc` library to the Matlab path](https://github.com/robotology/whole-body-controllers/issues/75)
- [x] [include forward dynamics block in the library](https://github.com/robotology/whole-body-controllers/issues/62)
- [x] [update documentation and wiki](https://github.com/robotology/whole-body-controllers/issues/55)
- [x] [add `gotowholebodycontrollers`](https://github.com/robotology/whole-body-controllers/issues/68)
 - [x] [update autogeneration of Simulink models](https://github.com/robotology/whole-body-controllers/pull/92)

**Comment by gabrielenava** [comment]
I've increased the priority of the release and of the associated issues, with the objective of doing a sprint and close the release.

**Comment by gabrielenava** [comment]
## CHANGELOG V2.5 (to be copied in the release description)

### New features

- added a data processing pipeline #20 
- added a Simulink model which also integrates the system's dynamics #62
- added home positions for the `yarpmotorgui` #80 

### Enhancements

- when a joint hits the limits or a spike is detected, the name of the joint is printed in a warning #81 
- it is possible now to skip recompilation of the model after a re-start when using the GUI #82 

### Documentation

- improved documentation for the release #55 
- added pictures of the Simulink models in the readmes #47 

### Installation

- now the `goToWholeBodyControllers.m` function is generated when calling `createGoToWBC.m` #75 
- Improved installation of the `wbc` library  #75 
- updated installation of autogenerated whole-body-controllers https://github.com/robotology/whole-body-controllers/pull/92

**Comment by gabrielenava** [comment]
Almost finished: when https://github.com/robotology/whole-body-controllers/pull/92 and https://github.com/robotology/robotology-superbuild/pull/367 will be merged, the `2.5` release will be done.

**Comment by traversaro** [comment]
> 
> 
> Almost finished: when #92 and [robotology/robotology-superbuild#367](https://github.com/robotology/robotology-superbuild/pull/367) will be merged, the `2.5` release will be done.

Not a blocker for the 2.5 release (actually it is a modification that needs to be done **after the 2.5 release), but I think we should also modify the superbuild to install whole-body-controllers also when `ROBOTOLOGY_USES_MATLAB` is disabled.

**Comment by gabrielenava** [comment]
## TODO after merging:

- create the release and update the  readme; :heavy_check_mark: 

- Modify the superbuild to install whole-body-controllers also when ROBOTOLOGY_USES_MATLAB is disabled;

- Update the superbuild and WBC documentation accordingly;

- Consistency check for all the hyperlinks in the readmes; :heavy_check_mark: 

- Add link to the new Simulink-only controller in the wiki. :heavy_check_mark:

**Comment by gabrielenava** [comment]
>Not a blocker for the 2.5 release (actually it is a modification that needs to be done **after the 2.5 release), but I think we should also modify the superbuild to install whole-body-controllers also when ROBOTOLOGY_USES_MATLAB is disabled.

@traversaro I was addressing this point but I have some questions:

- Looking at the [CMakeLists](https://github.com/robotology/robotology-superbuild/blob/master/CMakeLists.txt#L160) of `robotology-superbuild`, there is also the option `ROBOTOLOGY_NOT_USE_SIMULINK`. Should I bring whole-body-controllers out of both the tags? do we still need the `ROBOTOLOGY_NOT_USE_SIMULINK` tag or it can be removed (it seems it is used only in that line);

- So if I install `whole-body-controllers` without Matlab on my pc, it should just clone the repo and install the home positions and the library. The option for autogeneration is OFF, but what happens if a user turn it on without Matlab? should we consider also this hypothesis?

- I think we should also document in the superbuild README that if WBC is installed without Matlab, its functionalities are reduced.

**Comment by traversaro** [comment]
>  Looking at the CMakeLists of robotology-superbuild, there is also the option ROBOTOLOGY_NOT_USE_SIMULINK. Should I bring whole-body-controllers out of both the tags? do we still need the ROBOTOLOGY_NOT_USE_SIMULINK tag or it can be removed (it seems it is used only in that line);

Mhh, `ROBOTOLOGY_NOT_USE_SIMULINK` is useful for avoiding failures in BlockFactory if Matlab is compiled but Simulink is not, the fact that is used only there sounds like a regression. Probably the USES_MATLAB option of BlockFactory (see https://github.com/robotology/robotology-superbuild/blob/bdf3b7c5f4d7d2531e8c566058937558f23de649/cmake/BuildBlockFactory.cmake#L13) should depend on the value of `ROBOTOLOGY_NOT_USE_SIMULINK`. However, this is unrelated.

> So if I install whole-body-controllers without Matlab on my pc, it should just clone the repo and install the home positions and the library. 

Yes. The reason we did  not install it in the past even if it was harmless do to so in a system where `ROBOTOLOGY_USES_MATLAB` is disabled was to save clone time and space on disk, but given that it is now useful we can just download and  install it in any case.

> The option for autogeneration is OFF, but what happens if a user turn it on without Matlab? should we consider also this hypothesis?

No, we only care for the default options and for the options that are exposed in the superbuild CMake.

> I think we should also document in the superbuild README that if WBC is installed without Matlab, its functionalities are reduced.

You can probably mention that either in the ROBOTOLOGY_ENABLE_DYNAMICS or ROBOTOLOGY_USES_MATLAB docs.

**Comment by gabrielenava** [comment]
[WBC readme](https://github.com/robotology/whole-body-controllers/blob/master/README.md#installation-and-usage) updated and [PR](https://github.com/robotology/robotology-superbuild/pull/370) opened. 

Once the PR will be finished, I'll close this issue and the 2.5 release will be officially concluded.

**Comment by gabrielenava** [comment]
The PR has been merged. Closing, the release is officially concluded.
