### ISSUE TITLE
Whole-body-controllers release 2.5.2

### ISSUE THREAD

**Issue by gabrielenava** [robotology/whole-body-controllers#94]
## RELEASE DATE: TBD

This issue is a tracker for the new WBC release 2.5.2.

Issues involved in the new release (list will be updated in the future):

~- [ ] [Fix bug in fromTransfMatrixToPosQuat](https://github.com/robotology/whole-body-controllers/issues/111)~
~- [ ] [Add KPI logic to evaluate performance and robustness of controllers](https://github.com/robotology/whole-body-controllers/issues/96)~
~- [ ] [Change the name of the repo](#109)~
- [X] [Added Momentum Based Velocity control as a new WBC Simulink library](#99 )
- [x] Update documentation for release 2.5.2
~- [ ] [Understand how to create standalone Simulink applications](https://github.com/robotology/whole-body-controllers/issues/91)~
~- [ ] [Implement a block to check if the measured forces violate the contact constraints](https://github.com/robotology/whole-body-controllers/issues/89)~
~- [ ] [Implement github actions](https://github.com/robotology/whole-body-controllers/issues/88)~
- [x] [Migrate the jerk control in whole-body-controllers](https://github.com/robotology/whole-body-controllers/issues/87)
~- [ ] [Simplify the simulation pipeline](https://github.com/robotology/whole-body-controllers/issues/76)~
~- [ ] [Import functions and remove deprecated in the WBC library](https://github.com/robotology/whole-body-controllers/issues/71)~
- [x] [Improve the Simulink-balancing-simulator](https://github.com/robotology/whole-body-controllers/issues/95)
~- [ ] [Create the controllers library with its first block: the YOGA++ controller](https://github.com/robotology/whole-body-controllers/issues/114)~
~- [ ] [Create a library of controller blocks out of the multiple models in this repo and integrate them in those models](https://github.com/robotology/whole-body-controllers/issues/113)~

**Comment by nunoguedelha** [comment]
Reopened since there is still the documentation to update.

**Comment by gabrielenava** [comment]
I modified the issue title and description so that the issue can be closed. #90 will be added in a new dedicated issue that triggers the release 3.0
